### PR TITLE
silence which warnings: 'no tntnet-config in (..)'

### PR DESCRIPTION
**Pull request by wirbel-at-vdr-portal**

### CODE REVIEW

**Comment by kfb77** [comment]
The which command was inserted with this commit https://github.com/MarkusEh/vdr-plugin-live/commit/c7f5f0b87bb08ef5265edc0e65096097d26809a1 because tntnet30 does no longer have this command.
I can not reproduce your issue. With OS du you use ?
On Ubuntu I get nothing, not even a error message, if I call which with a non existing command.

**Comment by wirbel-at-vdr-portal** [comment]
This is LinuxFromScratch plus BLFS, using which-2.21.

Makefile produces for every build

which: no tntnet-config in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/opt/xorg/bin)
which: no tntnet-config in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/opt/xorg/bin)

inside brackets is current PATH environment variable.

There are many possibilities to replace 'which' by shell scripts, i use the native binary.
Not so surprising that one some distris this doesnt show up.

**Comment by kfb77** [comment]
OK, nothing which I can reproduce.
I do not like removing all error output, sometimes they are usefull.
Would something like:
TNTNET-CONFIG := $(shell which tntnet-config 2>&1 |  grep -v "which: no tntnet-config")
help ?
Better in stdout than lost at all.

**Comment by wirbel-at-vdr-portal** [comment]
yes, works.

My solution just surpresses the  messages from stderr and leaves stdout untouched.
Your proposal redirects those err messages to stdout and filters them afterwards via grep.

As you like.

**Comment by kfb77** [comment]
Your solution surpresses all messages from stderr, even if command which is missing on the system.

We let decide the owner of the git: two solutions of one problem, both are working, one in this PR, one in branch Makefile.
@MarkusEh please decide and merge.

**Comment by MarkusEh** [comment]
Hi,
which behavior in case of non-existing commands depends on the shell.
If i understand correctly. older tnt versions do install tntnet-config, but tntnet30 does not install tntnet-config?
@kfb77 , can you confirm?

Markus

**Comment by kfb77** [comment]
Yes, I confirm.
"... even if command which is missing on the system", this was not very clear, i will try to clarify:
"... even if the 'which' command is missing on the system".

**Comment by MarkusEh** [comment]
Ich übernehme den PR von wirbel.
Normalerweise sollte man Fehler nicht ignorieren, das sehe ich auch so.
In diesen Fall ist das Fehlen von tntnet-config aber kein Fehler, sondern zeigt nur an, dass tntnet30 installiert ist.
Je nach shell gibt which dann eine Fehlermeldung aus, die auch noch von shell zu shell verschieden ist.
Diese Fehlermeldung zu unterdrücken ist OK.

**Pull request merged**
